import { loader } from '@monaco-editor/react';

import * as monaco from 'monaco-editor';
import editorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker';
import jsonWorker from 'monaco-editor/esm/vs/language/json/json.worker?worker';

self.MonacoEnvironment = {
  getWorker(_workerId, label) {
    if (label === 'json') {
      return new jsonWorker();
    }
    return new editorWorker();
  },
};

loader.config({ monaco });

// https://code.visualstudio.com/api/references/theme-color
// https://rodrigoluglio.github.io/vscode-theme-generator/
// https://gitlab.com/-/snippets/1728446
// https://github.com/microsoft/monaco-editor/blob/main/website/src/website/data/playground-samples/customizing-the-appearence/exposed-colors/sample.js

monaco.editor.setTheme("vs-dark");
const ed = monaco.editor;
console.log("ed", ed);

monaco.editor.defineTheme('pebkac-dark', {
  base: 'vs-dark',
  inherit: true,
  colors: {
    'editor.background': '#222222',
    // 'editor.foreground': '#00FF00',

    // 'foreground': '#00FF00',

    // 'editorIndentGuides.background': '#ff0000',
    // 'editorIndentGuide.activeBackground': '#ff0000',
    // 'editor.caret': '#ff0000',
    // 'editor.gutter': '#ff0000',
    // 'editor.invisibles': '#ff0000',
    // 'editor.lineHighlight': '#ff0000',
    // 'editor.selection': '#ff0000',
    // 'editor.inactiveSelection': '#ff0000',
    // 'editor.selectionBorder': '#ff0000',
    // 'editor.guide': '#ff0000',
    // 'editor.activeLinkForeground': '#ff0000',
    // 'editor.selectionHighlight': '#ff0000',
    // 'editor
    // .hoverHighlight': '#ff0000',
    // 'editor.findMatchHighlight': '#ff0000',
    // 'editor.currentFindMatchHighlight': '#ff0000',
    // 'editor.wordHighlight': '#ff0000',
    // 'editor.wordHighlightStrong': '#ff0000',
    // 'editor.referenceHighlight': '#ff0000',
    // 'editor.rangeHighlight': '#ff0000',
    // 'editor.findRangeHighlight': '#ff0000',


    
  },
  rules: [
      {
        "token": "",
        "foreground": "ff0000",
        "background": "0000ff"
      },

    { token: 'comment', foreground: '#ff0000' },
    { token: 'meta.documentation', foreground: '#ff0000' },
    { token: 'string', foreground: '#ff0000' },
    { token: 'string.regexp', foreground: '#ff0000' },
    { token: 'constant.character.escape', foreground: '#ff0000' },
    { token: 'constant.numeric', foreground: '#ff0000' },
    { token: 'variable', foreground: '#ff0000' },
    { token: 'variable.other.readwrite', foreground: '#ff0000' },
    { token: 'variable.other.object', foreground: '#ff0000' },
    { token: 'variable.other.constant', foreground: '#ff0000' },
    { token: 'variable.function', foreground: '#ff0000' },
    { token: 'variable.language.this', foreground: '#ff0000' },
    { token: 'variable.language.super', foreground: '#ff0000' },
    { token: 'keyword', foreground: '#ff0000' },
    { token: 'meta.import keyword', foreground: '#ff0000' },
    { token: 'keyword.control.import', foreground: '#ff0000' },
    { token: 'keyword.control.import.from', foreground: '#ff0000' },
    { token: 'keyword.other.import', foreground: '#ff0000' },
    { token: 'keyword.control.at-rule.include', foreground: '#ff0000' },
    { token: 'keyword.control.at-rule.import', foreground: '#ff0000' },
    { token: 'keyword.operator.comparison', foreground: '#ff0000' },
    { token: 'keyword.operator.assignment', foreground: '#ff0000' },
    { token: 'keyword.operator.arithmetic', foreground: '#ff0000' },
    { token: 'storage', foreground: '#ff0000' },
    { token: 'keyword.control.class', foreground: '#ff0000' },
    { token: 'meta.class', foreground: '#ff0000' },
    { token: 'entity.name.class', foreground: '#ff0000' },
    { token: 'entity.name.type.class', foreground: '#ff0000' },
    { token: 'support.type', foreground: '#ff0000' },
    { token: 'support.class', foreground: '#ff0000' },
    { token: 'entity.name.function', foreground: '#ff0000' },
    { token: 'punctuation.definition.variable', foreground: '#ff0000' },
    { token: 'constant.language', foreground: '#ff0000' },
    { token: 'meta.preprocessor', foreground: '#ff0000' },
    { token: 'support.function.construct', foreground: '#ff0000' },
    { token: 'keyword.other.new', foreground: '#ff0000' },
    { token: 'constant.character', foreground: '#ff0000' },
    { token: 'constant.other', foreground: '#ff0000' },
    { token: 'entity.name.tag', foreground: '#ff0000' },
    { token: 'punctuation.definition.tag.html', foreground: '#ff0000' },
    { token: 'punctuation.definition.tag.begin', foreground: '#ff0000' },
    { token: 'punctuation.definition.tag.end', foreground: '#ff0000' },
    { token: 'support.function', foreground: '#ff0000' },
    { token: 'punctuation.separator.continuation', foreground: '#ff0000' },
    { token: 'storage.type', foreground: '#ff0000' },
    { token: 'support.type.exception', foreground: '#ff0000' },
    { token: 'keyword.other.special-method', foreground: '#ff0000' },
    { token: 'string.quoted.double', foreground: '#ff0000' },
    { token: 'string.quoted.single', foreground: '#ff0000' },
    { token: 'punctuation.definition.string.begin', foreground: '#ff0000' },
    { token: 'punctuation.definition.string.end', foreground: '#ff0000' },
    { token: 'meta.brace.square', foreground: '#ff0000' },
    { token: 'meta.brace.round', foreground: '#ff0000' },
    { token: 'punctuation.definition.parameters.begin', foreground: '#ff0000' },
    { token: 'punctuation.definition.parameters.end', foreground: '#ff0000' },
    { token: 'meta.brace.curly', foreground: '#ff0000' },
    { token: 'support.constant.color', foreground: '#ff0000' },
    { token: 'invalid.deprecated.color.w3c-non-standard-color-name.scss', foreground: '#ff0000' },
    { token: 'meta.selector.css', foreground: '#ff0000' },
    { token: 'entity.name.tag.css', foreground: '#ff0000' },
    { token: 'entity.name.tag.scss', foreground: '#ff0000' },
    { token: 'source.less keyword.control.html.elements', foreground: '#ff0000' },
    { token: 'source.sass keyword.control.untitled', foreground: '#ff0000' },
    { token: 'entity.other.attribute-name.class.css', foreground: '#ff0000' },
    { token: 'entity.other.attribute-name.class.sass', foreground: '#ff0000' },
    { token: 'source.css entity.other.attribute-name.id', foreground: '#ff0000' },
    { token: 'source.less entity.other.attribute-name.id', foreground: '#ff0000' },
    { token: 'source.scss entity.other.attribute-name.id', foreground: '#ff0000' },
    { token: 'source.sass entity.other.attribute-name.id', foreground: '#ff0000' },
    { token: 'entity.other.attribute-name.pseudo-element.css', foreground: '#ff0000' },
    { token: 'entity.other.attribute-name.pseudo-class', foreground: '#ff0000' },
    { token: 'entity.other.attribute-name.tag.pseudo-class', foreground: '#ff0000' },
    { token: 'text.html.basic meta.tag.other.html', foreground: '#ff0000' },
    { token: 'text.html.basic meta.tag.any.html', foreground: '#ff0000' },
    { token: 'text.html.basic meta.tag.block.any', foreground: '#ff0000' },
    { token: 'text.html.basic meta.tag.inline.any', foreground: '#ff0000' },
    { token: 'text.html.basic meta.tag.structure.any.html', foreground: '#ff0000' },
    { token: 'text.html.basic source.js.embedded.html', foreground: '#ff0000' },
    { token: 'punctuation.separator.key-value.html', foreground: '#ff0000' },
    { token: 'text.html.basic entity.other.attribute-name.html', foreground: '#ff0000' },
    { token: 'meta.tag.xml entity.other.attribute-name', foreground: '#ff0000' },
    { token: 'keyword.other.special-method.ruby', foreground: '#ff0000' },
    { token: 'variable.other.constant.ruby', foreground: '#ff0000' },
    { token: 'constant.other.symbol.ruby', foreground: '#ff0000' },
    { token: 'keyword.other.special-method.ruby', foreground: '#ff0000' },
    { token: 'meta.array support.function.construct.php', foreground: '#ff0000' },
    { token: 'entity.name.function.preprocessor.c', foreground: '#ff0000' },
    { token: 'meta.preprocessor.c.include', foreground: '#ff0000' },
    { token: 'meta.preprocessor.macro.c', foreground: '#ff0000' },
    { token: 'meta.preprocessor.c.include string', foreground: '#ff0000' },
    { token: 'meta.preprocessor.c.include punctuation.definition.string.begin', foreground: '#ff0000' },
    { token: 'meta.preprocessor.c.include punctuation.definition.string.end', foreground: '#ff0000' },
    { token: 'other.package.exclude', foreground: '#ff0000' },
    { token: 'other.remove', foreground: '#ff0000' },
    { token: 'other.add', foreground: '#ff0000' },
    { token: 'punctuation.section.group.tex', foreground: '#ff0000' },
    { token: 'punctuation.definition.arguments.begin.latex', foreground: '#ff0000' },
    { token: 'punctuation.definition.arguments.end.latex', foreground: '#ff0000' },
    { token: 'punctuation.definition.arguments.latex', foreground: '#ff0000' },
    { token: 'meta.group.braces.tex', foreground: '#ff0000' },
    { token: 'string.other.math.tex', foreground: '#ff0000' },
    { token: 'variable.parameter.function.latex', foreground: '#ff0000' },
    { token: 'punctuation.definition.constant.math.tex', foreground: '#ff0000' },
    { token: 'text.tex.latex constant.other.math.tex', foreground: '#ff0000' },
    { token: 'constant.other.general.math.tex', foreground: '#ff0000' },
    { token: 'constant.other.general.math.tex', foreground: '#ff0000' },
    { token: 'constant.character.math.tex', foreground: '#ff0000' },
    { token: 'string.other.math.tex', foreground: '#ff0000' },
    { token: 'punctuation.definition.string.begin.tex', foreground: '#ff0000' },
    { token: 'punctuation.definition.string.end.tex', foreground: '#ff0000' },
    { token: 'keyword.control.label.latex', foreground: '#ff0000' },
    { token: 'text.tex.latex constant.other.general.math.tex', foreground: '#ff0000' },
    { token: 'variable.parameter.definition.label.latex', foreground: '#ff0000' },
    { token: 'support.function.be.latex', foreground: '#ff0000' },
    { token: 'support.function.section.latex', foreground: '#ff0000' },
    { token: 'support.function.general.tex', foreground: '#ff0000' },
    { token: 'keyword.control.ref.latex', foreground: '#ff0000' },
    { token: 'storage.type.class.python', foreground: '#ff0000' },
    { token: 'storage.type.function.python', foreground: '#ff0000' },
    { token: 'storage.modifier.global.python', foreground: '#ff0000' },
    { token: 'support.type.exception.python', foreground: '#ff0000' },
    { token: 'meta.scope.for-in-loop.shell', foreground: '#ff0000' },
    { token: 'variable.other.loop.shell', foreground: '#ff0000' },
    { token: 'meta.scope.case-block.shell', foreground: '#ff0000' },
    { token: 'meta.scope.case-body.shell', foreground: '#ff0000' },
    { token: 'punctuation.definition.logical-expression.shell', foreground: '#ff0000' },
    { token: 'storage.modifier.import.java', foreground: '#ff0000' },
    { token: 'support.function.perl', foreground: '#ff0000' },
    { token: 'meta.diff', foreground: '#ff0000' },
    { token: 'meta.diff.header', foreground: '#ff0000' },
    { token: 'meta.diff.range', foreground: '#ff0000' },
    { token: 'markup.deleted', foreground: '#ff0000' },
    { token: 'markup.changed', foreground: '#ff0000' },
    { token: 'markup.inserted', foreground: '#ff0000' },
    { token: 'markup.heading', foreground: '#ff0000' },
    { token: 'punctuation.definition.heading.markdown', foreground: '#ff0000' },
    { token: 'markup.quote', foreground: '#ff0000' },
    { token: 'markup.underline.link.markdown', foreground: '#ff0000' },
    { token: 'meta.link.reference constant.other.reference.link.markdown', foreground: '#ff0000' },
    { token: 'constant.other.reference.link.markdown', foreground: '#ff0000' },
    { token: 'sublimelinter.mark.warning', foreground: '#ff0000' },
    { token: 'sublimelinter.mark.error', foreground: '#ff0000' },
    { token: 'sublimelinter.gutter-mark', foreground: '#ff0000' },
    { token: 'brackethighlighter.all', foreground: '#ff0000' },
    { token: 'entity.name.filename.find-in-files', foreground: '#ff0000' },
    { token: 'constant.numeric.line-number.find-in-files', foreground: '#ff0000' },
    { token: 'markup.deleted.git_gutter', foreground: '#ff0000' },
    { token: 'markup.inserted.git_gutter', foreground: '#ff0000' },
    { token: 'markup.changed.git_gutter', foreground: '#ff0000' },
    { token: 'meta.class punctuation', foreground: '#ff0000' },
  ],

  // rules: [
  // { token: 'custom-info', foreground: 'a3a7a9', background: 'ffffff' },
  // { token: 'custom-error', foreground: 'ee4444' },
  // { token: 'custom-notice', foreground: '1055af' },
  // { token: 'custom-date', foreground: '20aa20' },
  // ]
});